# Generated by Django 4.2.2 on 2023-06-15 19:56

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roxy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('content', ckeditor.fields.RichTextField()),
                ('img', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(choices=[('CODE', 'CODE'), ('SPORTS', 'SPORTS'), ('ECONOMY', 'ECONOMY')], max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.CharField(max_length=100)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roxy.page')),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('img', models.ImageField(upload_to='')),
                ('comments_no', models.PositiveBigIntegerField()),
                ('content', models.TextField(max_length=100)),
                ('by', models.CharField(max_length=50)),
                ('twitter', models.URLField()),
                ('facebook', models.URLField()),
                ('page', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='roxy.page')),
                ('tag', models.ManyToManyField(to='roxy.tag')),
            ],
        ),
    ]
