# Generated by Django 4.2.2 on 2023-06-16 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roxy', '0002_page_tag_comment_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='img',
            field=models.ImageField(upload_to='card'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='page'),
        ),
    ]
