# Generated by Django 4.2.2 on 2023-06-17 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roxy', '0004_photos_testimonial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(choices=[('Vintage', 'Vintage'), ('Creative', 'Creative')], max_length=50)),
                ('img', models.ImageField(upload_to='portfolio')),
            ],
        ),
        migrations.DeleteModel(
            name='Photos',
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='img',
            field=models.ImageField(blank=True, default='testimonial/default.png', null=True, upload_to='testimonial'),
        ),
    ]
