# Generated by Django 4.2.2 on 2023-06-17 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roxy', '0005_portfolio_delete_photos_alter_testimonial_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='choice',
            field=models.CharField(choices=[('Vintage', 'Vintage'), ('Creative', 'Creative'), ('Minimalism', 'Minimalism')], max_length=50),
        ),
    ]
