# Generated by Django 4.2.2 on 2023-06-17 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roxy', '0006_alter_portfolio_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='description',
            field=models.CharField(default='Default', max_length=50),
        ),
    ]
