# Generated by Django 4.2.1 on 2023-05-27 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='gravatar_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
