# Generated by Django 4.2.1 on 2023-05-25 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MovieData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('year', models.IntegerField()),
                ('description', models.TextField()),
                ('rating', models.PositiveSmallIntegerField()),
                ('ranking', models.PositiveSmallIntegerField()),
                ('review', models.CharField(max_length=250)),
                ('img_url', models.URLField()),
            ],
        ),
    ]
